/*-
 * ===============LICENSE_START=======================================================
 * Acumos
 * ===================================================================================
 * Copyright (C) 2017 - 2018 AT&T Intellectual Property & Tech Mahindra. All rights reserved.
 * ===================================================================================
 * This Acumos software file is distributed by AT&T and Tech Mahindra
 * under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *      http://www.apache.org/licenses/LICENSE-2.0
 *  
 * This file is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ===============LICENSE_END=========================================================
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: default.proto

package org.acumos.vo;

public final class DataVO {
  private DataVO() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface inputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.acumos.input)
      com.google.protobuf.MessageOrBuilder {
	  
	 
	  

    /**
     * <code>repeated int32 id = 1;</code>
     */
	  /**
	   * @return
	   * This will return IdList
	   */
    java.util.List<java.lang.Integer> getIdList();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    /**
     * 
     * @return
     * This will return int
     */
    int getIdCount();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    /**
     * 
     * @param index
     * 		This method accepts index
     * @return
     * This will return int
     */
    int getId(int index);

    /**
     * <code>repeated string name = 2;</code>
     */
    /**
     * @return
     * This will return list of String
     */
    java.util.List<java.lang.String>
        getNameList();
    /**
     * <code>repeated string name = 2;</code>
     */
    /**
     * 
     * @return
     * This will return int
     */
    int getNameCount();
    /**
     * <code>repeated string name = 2;</code>
     */
    /**
     * 
     * @param index
     * 		This method accepts index
     * @return
     * This will return String
     */
    java.lang.String getName(int index);
    /**
     * <code>repeated string name = 2;</code>
     */
    /**
     * 
     * @param index
     * 			This method accepts index
     * @return
     * This will return ByteString
     */
    com.google.protobuf.ByteString
        getNameBytes(int index);

    /**
     * <code>repeated int32 address = 3;</code>
     */
    /**
     * 
     * @return
     * This will return list of Integer
     */
    java.util.List<java.lang.Integer> getAddressList();
    /**
     * <code>repeated int32 address = 3;</code>
     */
    /**
     * 
     * @return
     * This will return int
     */
    int getAddressCount();
    /**
     * <code>repeated int32 address = 3;</code>
     */
    /**
     * 
     * @param index
     * 		This method accepts index
     * @return
     * This will return int
     */
    int getAddress(int index);
  }
  /**
   * Protobuf type {@code org.acumos.input}
   */
  public  static final class input extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.acumos.input)
      inputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use input.newBuilder() to construct.
    private input(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private input() {
      id_ = java.util.Collections.emptyList();
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      address_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private input(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                id_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                name_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              name_.add(bs);
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                address_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              address_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                address_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                address_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = name_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          address_ = java.util.Collections.unmodifiableList(address_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.acumos.vo.DataVO.internal_static_org_acumos_input_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.acumos.vo.DataVO.internal_static_org_acumos_input_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.acumos.vo.DataVO.input.class, org.acumos.vo.DataVO.input.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> id_;
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getId(int index) {
      return id_.get(index);
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList name_;
    /**
     * <code>repeated string name = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNameList() {
      return name_;
    }
    /**
     * <code>repeated string name = 2;</code>
     */
    public int getNameCount() {
      return name_.size();
    }
    /**
     * <code>repeated string name = 2;</code>
     */
    public java.lang.String getName(int index) {
      return name_.get(index);
    }
    /**
     * <code>repeated string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes(int index) {
      return name_.getByteString(index);
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> address_;
    /**
     * <code>repeated int32 address = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getAddressList() {
      return address_;
    }
    /**
     * <code>repeated int32 address = 3;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated int32 address = 3;</code>
     */
    public int getAddress(int index) {
      return address_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < id_.size(); i++) {
        output.writeInt32(1, id_.get(i));
      }
      for (int i = 0; i < name_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_.getRaw(i));
      }
      for (int i = 0; i < address_.size(); i++) {
        output.writeInt32(3, address_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(id_.get(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += computeStringSizeNoTag(name_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < address_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(address_.get(i));
        }
        size += dataSize;
        size += 1 * getAddressList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.acumos.vo.DataVO.input)) {
        return super.equals(obj);
      }
      org.acumos.vo.DataVO.input other = (org.acumos.vo.DataVO.input) obj;

      boolean result = true;
      result = result && getIdList()
          .equals(other.getIdList());
      result = result && getNameList()
          .equals(other.getNameList());
      result = result && getAddressList()
          .equals(other.getAddressList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdCount() > 0) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getIdList().hashCode();
      }
      if (getNameCount() > 0) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getNameList().hashCode();
      }
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.acumos.vo.DataVO.input parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acumos.vo.DataVO.input parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.input parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acumos.vo.DataVO.input parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.input parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acumos.vo.DataVO.input parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.input parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.acumos.vo.DataVO.input parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.input parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.acumos.vo.DataVO.input parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.input parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.acumos.vo.DataVO.input parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.acumos.vo.DataVO.input prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.acumos.input}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.acumos.input)
        org.acumos.vo.DataVO.inputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.acumos.vo.DataVO.internal_static_org_acumos_input_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.acumos.vo.DataVO.internal_static_org_acumos_input_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.acumos.vo.DataVO.input.class, org.acumos.vo.DataVO.input.Builder.class);
      }

      // Construct using org.acumos.vo.DataVO.input.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.acumos.vo.DataVO.internal_static_org_acumos_input_descriptor;
      }

      public org.acumos.vo.DataVO.input getDefaultInstanceForType() {
        return org.acumos.vo.DataVO.input.getDefaultInstance();
      }

      public org.acumos.vo.DataVO.input build() {
        org.acumos.vo.DataVO.input result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.acumos.vo.DataVO.input buildPartial() {
        org.acumos.vo.DataVO.input result = new org.acumos.vo.DataVO.input(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = name_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          address_ = java.util.Collections.unmodifiableList(address_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.acumos.vo.DataVO.input) {
          return mergeFrom((org.acumos.vo.DataVO.input)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.acumos.vo.DataVO.input other) {
        if (other == org.acumos.vo.DataVO.input.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.acumos.vo.DataVO.input parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.acumos.vo.DataVO.input) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> id_ = java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<java.lang.Integer>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * 
       * @param index
       * 		This method accepts index
       * @param value
       * 		This method accepts value
       * @return
       * This will return builder
       */
      public Builder setId(
          int index, int value) {
        ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * 
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addId(int value) {
        ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * 
       * @param values
       * 		This method accepts values
       * @return
       * This will return Builder
       */
      public Builder addAllId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * @return
       * This will return Builder
       */
      public Builder clearId() {
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNameList() {
        return name_.getUnmodifiableView();
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public int getNameCount() {
        return name_.size();
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public java.lang.String getName(int index) {
        return name_.get(index);
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes(int index) {
        return name_.getByteString(index);
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param index
       * 		This method accepts index
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder setName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param values
       * 			This method accepts values
       * @return
       * This will return Builder
       */
      public Builder addAllName(
          java.lang.Iterable<java.lang.String> values) {
        ensureNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, name_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @return
       * This will return Builder
       */
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> address_ = java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          address_ = new java.util.ArrayList<java.lang.Integer>(address_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getAddressList() {
        return java.util.Collections.unmodifiableList(address_);
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      public int getAddressCount() {
        return address_.size();
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      public int getAddress(int index) {
        return address_.get(index);
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @param index
       * 		This method accepts index
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder 
       */
      public Builder setAddress(
          int index, int value) {
        ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @param value
       * 	This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addAddress(int value) {
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @param values
       * 	This method accepts values
       * @return
       * This will return Builder
       */

      public Builder addAllAddress(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @return
       * This will return Builder
       */
      public Builder clearAddress() {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.acumos.input)
    }

    // @@protoc_insertion_point(class_scope:org.acumos.input)
    private static final org.acumos.vo.DataVO.input DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.acumos.vo.DataVO.input();
    }

    public static org.acumos.vo.DataVO.input getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<input>
        PARSER = new com.google.protobuf.AbstractParser<input>() {
      public input parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new input(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<input> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<input> getParserForType() {
      return PARSER;
    }

    public org.acumos.vo.DataVO.input getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface outputOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.acumos.output)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 id = 1;</code>
     */
	  /**
	   * 
	   * @return
	   * This will return list of integer
	   */
    java.util.List<java.lang.Integer> getIdList();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    /**
     * 
     * @return
     * This will return int
     */
    int getIdCount();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    /**
     * 
     * @param index
     * 		This method accepts index
     * @return
     * This will return int
     */
    int getId(int index);

    /**
     * <code>repeated string name = 2;</code>
     */
    /**
     *
     * @return
     * This will return list of String
     */
    java.util.List<java.lang.String>
        getNameList();
    
    /**
     * Get the name count
     * @return
     * 		returns int value
     */
    int getNameCount();
    /**
     * <code>repeated string name = 2;</code>
     */
    /**
     * 
     * @param index
     * 		This method accepts index
     * @return
     * This will return String
     */
    java.lang.String getName(int index);
    /**
     * <code>repeated string name = 2;</code>
     */
    /**
     * 
     * @param index
     * 			This method accepts index
     * @return
     * This will return ByteString
     */
    com.google.protobuf.ByteString
        getNameBytes(int index);

    /**
     * <code>repeated int32 address = 3;</code>
     */
    /**
     * 
     * @return
     * This will return List of Integer
     */
    java.util.List<java.lang.Integer> getAddressList();
    /**
     * <code>repeated int32 address = 3;</code>
     */
    /**
     * 
     * @return
     * This will return int
     */
    int getAddressCount();
    /**
     * <code>repeated int32 address = 3;</code>
     */
    /**
     * 
     * @param index
     * 		This method accepts index
     * @return
     * This will return int
     */
    int getAddress(int index);
  }
  /**
   * Protobuf type {@code org.acumos.output}
   */
  public  static final class output extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.acumos.output)
      outputOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use output.newBuilder() to construct.
    private output(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private output() {
      id_ = java.util.Collections.emptyList();
      name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      address_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private output(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                id_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                name_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              name_.add(bs);
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                address_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              address_.add(input.readInt32());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
                address_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              while (input.getBytesUntilLimit() > 0) {
                address_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = name_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          address_ = java.util.Collections.unmodifiableList(address_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.acumos.vo.DataVO.internal_static_org_acumos_output_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.acumos.vo.DataVO.internal_static_org_acumos_output_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.acumos.vo.DataVO.output.class, org.acumos.vo.DataVO.output.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> id_;
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getId(int index) {
      return id_.get(index);
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList name_;
    /**
     * <code>repeated string name = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNameList() {
      return name_;
    }
    /**
     * <code>repeated string name = 2;</code>
     */
    public int getNameCount() {
      return name_.size();
    }
    /**
     * <code>repeated string name = 2;</code>
     */
    public java.lang.String getName(int index) {
      return name_.get(index);
    }
    /**
     * <code>repeated string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes(int index) {
      return name_.getByteString(index);
    }

    public static final int ADDRESS_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> address_;
    /**
     * <code>repeated int32 address = 3;</code>
     */
    public java.util.List<java.lang.Integer>
        getAddressList() {
      return address_;
    }
    /**
     * <code>repeated int32 address = 3;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <code>repeated int32 address = 3;</code>
     */
    public int getAddress(int index) {
      return address_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < id_.size(); i++) {
        output.writeInt32(1, id_.get(i));
      }
      for (int i = 0; i < name_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_.getRaw(i));
      }
      for (int i = 0; i < address_.size(); i++) {
        output.writeInt32(3, address_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(id_.get(i));
        }
        size += dataSize;
        size += 1 * getIdList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < name_.size(); i++) {
          dataSize += computeStringSizeNoTag(name_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNameList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < address_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(address_.get(i));
        }
        size += dataSize;
        size += 1 * getAddressList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.acumos.vo.DataVO.output)) {
        return super.equals(obj);
      }
      org.acumos.vo.DataVO.output other = (org.acumos.vo.DataVO.output) obj;

      boolean result = true;
      result = result && getIdList()
          .equals(other.getIdList());
      result = result && getNameList()
          .equals(other.getNameList());
      result = result && getAddressList()
          .equals(other.getAddressList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdCount() > 0) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getIdList().hashCode();
      }
      if (getNameCount() > 0) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getNameList().hashCode();
      }
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.acumos.vo.DataVO.output parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acumos.vo.DataVO.output parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.output parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acumos.vo.DataVO.output parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.output parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.acumos.vo.DataVO.output parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.output parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.acumos.vo.DataVO.output parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.output parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.acumos.vo.DataVO.output parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.acumos.vo.DataVO.output parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.acumos.vo.DataVO.output parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.acumos.vo.DataVO.output prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.acumos.output}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.acumos.output)
        org.acumos.vo.DataVO.outputOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.acumos.vo.DataVO.internal_static_org_acumos_output_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.acumos.vo.DataVO.internal_static_org_acumos_output_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.acumos.vo.DataVO.output.class, org.acumos.vo.DataVO.output.Builder.class);
      }

      // Construct using org.acumos.vo.DataVO.output.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.acumos.vo.DataVO.internal_static_org_acumos_output_descriptor;
      }

      public org.acumos.vo.DataVO.output getDefaultInstanceForType() {
        return org.acumos.vo.DataVO.output.getDefaultInstance();
      }

      public org.acumos.vo.DataVO.output build() {
        org.acumos.vo.DataVO.output result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.acumos.vo.DataVO.output buildPartial() {
        org.acumos.vo.DataVO.output result = new org.acumos.vo.DataVO.output(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = name_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.name_ = name_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          address_ = java.util.Collections.unmodifiableList(address_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.address_ = address_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.acumos.vo.DataVO.output) {
          return mergeFrom((org.acumos.vo.DataVO.output)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.acumos.vo.DataVO.output other) {
        if (other == org.acumos.vo.DataVO.output.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        if (!other.name_.isEmpty()) {
          if (name_.isEmpty()) {
            name_ = other.name_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureNameIsMutable();
            name_.addAll(other.name_);
          }
          onChanged();
        }
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.acumos.vo.DataVO.output parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.acumos.vo.DataVO.output) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> id_ = java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<java.lang.Integer>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * 
       * @param index
       * 		This method accepts index
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder setId(
          int index, int value) {
        ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * 
       * @param value 	
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addId(int value) {
        ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * 
       * @param values
       * 		This method accepts values
       * @return
       * This will return Builder
       */
      public Builder addAllId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      /**
       * 
       * @return
       * This will return Builder
       */
      public Builder clearId() {
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNameIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          name_ = new com.google.protobuf.LazyStringArrayList(name_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNameList() {
        return name_.getUnmodifiableView();
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public int getNameCount() {
        return name_.size();
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public java.lang.String getName(int index) {
        return name_.get(index);
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes(int index) {
        return name_.getByteString(index);
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param index
       * 		This method accepts index
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder setName(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param value
       * 	This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param values
       * 	This method accepts values
       * @return
       * This will return Builder
       */
      public Builder addAllName(
          java.lang.Iterable<java.lang.String> values) {
        ensureNameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, name_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @return
       * This will return Builder
       */
      public Builder clearName() {
        name_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string name = 2;</code>
       */
      /**
       * 
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNameIsMutable();
        name_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> address_ = java.util.Collections.emptyList();
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          address_ = new java.util.ArrayList<java.lang.Integer>(address_);
          bitField0_ |= 0x00000004;
         }
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      public java.util.List<java.lang.Integer>
          getAddressList() {
        return java.util.Collections.unmodifiableList(address_);
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      public int getAddressCount() {
        return address_.size();
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      public int getAddress(int index) {
        return address_.get(index);
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @param index
       * 		This method accepts index
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder setAddress(
          int index, int value) {
        ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @param value
       * 		This method accepts value
       * @return
       * This will return Builder
       */
      public Builder addAddress(int value) {
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @param values
       * 	This method accepts values
       * @return
       * This will return Builder
       */
      public Builder addAllAddress(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 address = 3;</code>
       */
      /**
       * 
       * @return
       * This will return Builder
       */
      public Builder clearAddress() {
        address_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.acumos.output)
    }

    // @@protoc_insertion_point(class_scope:org.acumos.output)
    private static final org.acumos.vo.DataVO.output DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.acumos.vo.DataVO.output();
    }

    public static org.acumos.vo.DataVO.output getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<output>
        PARSER = new com.google.protobuf.AbstractParser<output>() {
      public output parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new output(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<output> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<output> getParserForType() {
      return PARSER;
    }

    public org.acumos.vo.DataVO.output getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_acumos_input_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_acumos_input_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_acumos_output_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_acumos_output_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rdefault.proto\022\norg.acumos\"2\n\005input\022\n\n\002" +
      "id\030\001 \003(\005\022\014\n\004name\030\002 \003(\t\022\017\n\007address\030\003 \003(\005\"" +
      "3\n\006output\022\n\n\002id\030\001 \003(\005\022\014\n\004name\030\002 \003(\t\022\017\n\007a" +
      "ddress\030\003 \003(\0052>\n\nDataMapper\0220\n\007mapData\022\021." +
      "org.acumos.input\032\022.org.acumos.outputB\027\n\r" +
      "org.acumos.voB\006DataVO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_acumos_input_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_acumos_input_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_acumos_input_descriptor,
        new java.lang.String[] { "Id", "Name", "Address", });
    internal_static_org_acumos_output_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_acumos_output_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_acumos_output_descriptor,
        new java.lang.String[] { "Id", "Name", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
